- name: change route53
  route53:
    state: present
    zone: testudacitylukaslee.com
    record: www.testudacitylukaslee.com
    failover: PRIMARY
    type: CNAME
    ttl: 30
    identifier: server1
    private_zone: yes
    overwrite: yes
    value: "{{ NEW_ALIAS }}"
    wait: yes
    health_check: "ec9f7e47-a6fb-4865-b4e4-aa6f94b75381"
